# Generated by Django 4.2.7 on 2023-12-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anteojo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=20)),
                ('tamanio', models.CharField(max_length=20)),
            ],
        ),
    ]
