# Generated by Django 4.2.7 on 2023-12-31 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anteojos', '0002_anteojo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='anteojo',
            name='fecha_de_venta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
