# Generated by Django 4.2.7 on 2023-12-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anillos', '0002_anillo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anillo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/imagenes_anillos'),
        ),
    ]
