# Generated by Django 4.2.7 on 2023-12-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/imagenes_clientes'),
        ),
    ]
